# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85f6275d2a6279938e5f77232d40503e21a1511a5e1e60d5439c6cc0705d33e522c9de0d71d748ce92c34f70d43ba5cf741122cb7d449aa451aa2fa2587e20c1

test:
  secret_key_base: 9f4bce74fdacfd6d96e2b7a7e8ddfda01fdaa92d528764e193441ba8b49d3e76956a0f7790c018092733c26888b6802d1e074b6cc67bebb87806efdb5e6f6247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
